CREATE TABLE friends
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    create_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    sender_user_id   BIGINT                                  NOT NULL,
    receiver_user_id BIGINT                                  NOT NULL,
    status           VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_friends PRIMARY KEY (id)
);

CREATE TABLE groups
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_groups PRIMARY KEY (id)
);

CREATE TABLE members
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    group_role_type   VARCHAR(255)                            NOT NULL,
    invitation_status VARCHAR(255)                            NOT NULL,
    user_id           BIGINT                                  NOT NULL,
    group_id          BIGINT                                  NOT NULL,
    CONSTRAINT pk_members PRIMARY KEY (id)
);

CREATE TABLE messages
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    media_url      VARCHAR(255),
    content        VARCHAR(255)                            NOT NULL,
    send_at        TIMESTAMP WITHOUT TIME ZONE,
    read_at        TIMESTAMP WITHOUT TIME ZONE,
    status         VARCHAR(255)                            NOT NULL,
    recipient_id   BIGINT                                  NOT NULL,
    recipient_type VARCHAR(255)                            NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_messages PRIMARY KEY (id)
);

CREATE TABLE privileges
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_privileges PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE roles_privileges
(
    privilege_id BIGINT NOT NULL,
    role_id      BIGINT NOT NULL,
    CONSTRAINT pk_roles_privileges PRIMARY KEY (privilege_id, role_id)
);

CREATE TABLE users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    create_at TIMESTAMP WITHOUT TIME ZONE,
    username  VARCHAR(255),
    password  VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE users_roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_users_roles PRIMARY KEY (role_id, user_id)
);

ALTER TABLE friends
    ADD CONSTRAINT FK_FRIENDS_ON_RECEIVER_USER FOREIGN KEY (receiver_user_id) REFERENCES users (id);

ALTER TABLE friends
    ADD CONSTRAINT FK_FRIENDS_ON_SENDER_USER FOREIGN KEY (sender_user_id) REFERENCES users (id);

ALTER TABLE members
    ADD CONSTRAINT FK_MEMBERS_ON_GROUP FOREIGN KEY (group_id) REFERENCES groups (id);

ALTER TABLE members
    ADD CONSTRAINT FK_MEMBERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE roles_privileges
    ADD CONSTRAINT fk_rolpri_on_privilege FOREIGN KEY (privilege_id) REFERENCES privileges (id);

ALTER TABLE roles_privileges
    ADD CONSTRAINT fk_rolpri_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_app_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES roles (id);